package de.greenrobot.daoexample;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table JUGADOR.
 */
public class Jugador {

    private Long id;
    /** Not-null value. */
    private String Nombre;
    /** Not-null value. */
    private String Apellido;
    /** Not-null value. */
    private java.util.Date fecha_nacimiento;

    public Jugador() {
    }

    public Jugador(Long id) {
        this.id = id;
    }

    public Jugador(Long id, String Nombre, String Apellido, java.util.Date fecha_nacimiento) {
        this.id = id;
        this.Nombre = Nombre;
        this.Apellido = Apellido;
        this.fecha_nacimiento = fecha_nacimiento;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return Nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    /** Not-null value. */
    public String getApellido() {
        return Apellido;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setApellido(String Apellido) {
        this.Apellido = Apellido;
    }

    /** Not-null value. */
    public java.util.Date getFecha_nacimiento() {
        return fecha_nacimiento;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFecha_nacimiento(java.util.Date fecha_nacimiento) {
        this.fecha_nacimiento = fecha_nacimiento;
    }

}
