package com.greenDao.esquema;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.greenDao.esquema.Jugador;
import com.greenDao.esquema.Equipo;
import com.greenDao.esquema.Partido;

import com.greenDao.esquema.JugadorDao;
import com.greenDao.esquema.EquipoDao;
import com.greenDao.esquema.PartidoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig jugadorDaoConfig;
    private final DaoConfig equipoDaoConfig;
    private final DaoConfig partidoDaoConfig;

    private final JugadorDao jugadorDao;
    private final EquipoDao equipoDao;
    private final PartidoDao partidoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        jugadorDaoConfig = daoConfigMap.get(JugadorDao.class).clone();
        jugadorDaoConfig.initIdentityScope(type);

        equipoDaoConfig = daoConfigMap.get(EquipoDao.class).clone();
        equipoDaoConfig.initIdentityScope(type);

        partidoDaoConfig = daoConfigMap.get(PartidoDao.class).clone();
        partidoDaoConfig.initIdentityScope(type);

        jugadorDao = new JugadorDao(jugadorDaoConfig, this);
        equipoDao = new EquipoDao(equipoDaoConfig, this);
        partidoDao = new PartidoDao(partidoDaoConfig, this);

        registerDao(Jugador.class, jugadorDao);
        registerDao(Equipo.class, equipoDao);
        registerDao(Partido.class, partidoDao);
    }
    
    public void clear() {
        jugadorDaoConfig.getIdentityScope().clear();
        equipoDaoConfig.getIdentityScope().clear();
        partidoDaoConfig.getIdentityScope().clear();
    }

    public JugadorDao getJugadorDao() {
        return jugadorDao;
    }

    public EquipoDao getEquipoDao() {
        return equipoDao;
    }

    public PartidoDao getPartidoDao() {
        return partidoDao;
    }

}
