package com.greenDao.esquema;

import java.util.List;
import com.greenDao.esquema.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table EQUIPO.
 */
public class Equipo {

    private Long id;
    /** Not-null value. */
    private String Nombre;
    /** Not-null value. */
    private String Categoria;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient EquipoDao myDao;

    private List<Partido> Partidos;

    public Equipo() {
    }

    public Equipo(Long id) {
        this.id = id;
    }

    public Equipo(Long id, String Nombre, String Categoria) {
        this.id = id;
        this.Nombre = Nombre;
        this.Categoria = Categoria;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getEquipoDao() : null;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getNombre() {
        return Nombre;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNombre(String Nombre) {
        this.Nombre = Nombre;
    }

    /** Not-null value. */
    public String getCategoria() {
        return Categoria;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCategoria(String Categoria) {
        this.Categoria = Categoria;
    }

    /** To-many relationship, resolved on first access (and after reset). Changes to to-many relations are not persisted, make changes to the target entity. */
    public List<Partido> getPartidos() {
        if (Partidos == null) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            PartidoDao targetDao = daoSession.getPartidoDao();
            List<Partido> PartidosNew = targetDao._queryEquipo_Partidos(id);
            synchronized (this) {
                if(Partidos == null) {
                    Partidos = PartidosNew;
                }
            }
        }
        return Partidos;
    }

    /** Resets a to-many relationship, making the next get call to query for a fresh result. */
    public synchronized void resetPartidos() {
        Partidos = null;
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

}
